name: build

on: 
  push:
  # activating dispatch while troubleshooting
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          make
          echo Build Complete
