name: build

on: 
  push:
  # activating dispatch while troubleshooting
  workflow_dispatch:

jobs:
  build_ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          make
          echo Build Complete
      - name: Archive toolchain
        uses: actions/upload-artifact@v3
        with:
          name: toolchain
          path: |
            bin
            include

  build_windows_2022:
    runs-on: windows-2022
    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          C:\msys64\msys2_shell.cmd -no-start -defterm -where %CD% -c "make"
          echo Build Complete
      - name: Archive toolchain
        uses: actions/upload-artifact@v3
        with:
          name: toolchain
          path: |
            bin
            include
            
            
